services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
      target: development
    user: "${USER_ID}:${USER_ID}"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/app
    environment:
      PHP_DATE_TIMEZONE: "${TIMEZONE}"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_NAME}
    volumes:
      - movary-database:/var/lib/mysql
      - ./storage/:/tmp/host
    ports:
      - "${DATABASE_MYSQL_PORT}:3306"

  mkdocs:
    image: squidfunk/mkdocs-material:latest
    ports:
      - 8000:8000
    volumes:
      - ./:/docs:ro

volumes:
  movary-database:
